### ISSUE TITLE
No enum constant

### ISSUE THREAD

**Issue by SvEgiiVEteR** [vidaj/BigTrees#1]
http://hastebin.com/puditipowi.md

**Comment by vidaj** [comment]
Did you change any of the tree configuration files and changed the algorithm setting? Or is there another non-config file in the treeconfiguration directory?

**Comment by SvEgiiVEteR** [comment]
it was necessary to delete the old config from the old version :) 
close

bad that the old version was configs
BIOM_BigTrees-172-BOP-configs.zip
Now they will not work ....

**Comment by vidaj** [comment]
Yeah, I've changed a lot of how the mod works now, so the old configs had to go. It should be easy enough to change your configs to work again, though. The treeconfig themselves have not changed that much. But there might be some tweaking to the biome distribution to get the old results, as there was no way to convert the old defaults to the new generation system. 
If you compare your old treeconfigs to the new, you should figure out quite easily what to change. The old meta flags are gone, as they are combined into the wood/leaf/baseblock as minecraft:log:2, for example. Locality has been renamed to noisefield, and frequencymultiplier has been removed.

I'll close this issue for now, but don't hesitate to comment again if you need help with your BOP config files.
