### ISSUE TITLE
[Question] config functions

### ISSUE THREAD

**Issue by Bogdan-G** [vidaj/BigTrees#2]
Hello. Thank you for the new version! 
Q1: why in the new version are not parsed biomes like the old? As well as not all the configuration is available in the old version?

At the moment, the older version is more flexible than the new settings, unfortunately it is. When do you plan to return all of their features or an improved version?

<hr>

Q2:
config section(file bigtrees.cfg):
`biometypes {
            S:Included <
                FOREST
             >
            S:Excluded <
             >
        }`
FOREST = minecraft.FOREST? If biomes have the same name in the BiomeDictionary, which a biome will be selected for the generation of mod?
Example: mod EXBL and vanilla: 
biome: `minecraft.Birch Forest` and biome: `extrabiomes.Birch Forest`
Two biome have the same name.
As a consequence: a proposal to make more of an explanation in the config.

**Comment by Zarzuf** [comment]
Actually, as I understand it, the new configuration is as flexible as the old, but a lot more tidy.
You can still select biomes both by biome dictionary group and by specific name. The only downside is that you have to know the specific name of biomes (you can use mods like NEI and No Id Conflicts to find the names).

The second question does not make sense. Some phrases lacks verbs and are really not understandable this way.

**Comment by Bogdan-G** [comment]
@Zarzuf I not completely fix what did Google translator.
P.s. Fix post.

**Comment by vidaj** [comment]
As @Zarzuf has said, the new configuration should be as flexible as the old, with a lot less config.
Most of the config is done with forge biome dictionary tags, so FOREST is any biome that is tagged as a forest. A list of vanilla biomes and tags can be found [here](https://www.reddit.com/r/biomesoplenty/comments/1ueued/request_list_of_forge_biome_dictionary_tags/)

I'm planning to set up a website for the mod to explain configs and such more in depth. I could also generate a file that contains the name of all the registered biomes. 

The main reason behind the changes is that the previous configs were quite verbose, confusing and not extendable. I have some cool plans going forward, for example biome specific overrides for wood types. The new configs (trees per chunk & chance per tree) are also more light weight than before. Before when decorating a forest biome, there were probably somewhere between 1000 and 2000 tries to generate a tree per chunk. With the new system, I would guess there's 10-15 tries.

**Comment by Bogdan-G** [comment]
@vidaj `FOREST` this tags? Ok, thanks :)
