### ISSUE TITLE
Chunk errors

### ISSUE THREAD

**Issue by vidaj** [vidaj/BigTrees#3]
The mod creates chunk errors where some chunks won't load on the client. Relogging usually helps, but this needs to be gone.

**Comment by vidaj** [comment]
Should be fixed in the following commits:
141521d60f3b2819508de0f6a9ed8b0de3e80f7b
13ca44d3a440c207bc56b4c9889dd082bb1e1b5c

**Comment by vidaj** [comment]
Released in v0.2

**Comment by Bogdan-G** [comment]
probably to blame mechanics vanilla
